create table credit
(
    id            BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    credit_amount DOUBLE PRECISION NOT NULL CHECK ( credit_amount > 0 ),
    percent_rate  DOUBLE PRECISION NOT NULL CHECK ( percent_rate > 0 ),
    credit_period INT              NOT NULL CHECK ( credit_period > 0 ),
    payment       DOUBLE PRECISION NOT NULL CHECK ( payment > 0 )
);

create table payment
(
    id               BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    payment_number   INT              NOT NULL CHECK ( payment_number > 0 ),
    payment_date     TIMESTAMP        NOT NULL,
    payment_amount   DOUBLE PRECISION NOT NULL CHECK ( payment_amount > 0 ),
    percent          DOUBLE PRECISION NOT NULL CHECK ( percent > 0 ),
    repayment_credit DOUBLE PRECISION NOT NULL CHECK ( repayment_credit > 0 ),
    remaining_credit DOUBLE PRECISION NOT NULL CHECK ( repayment_credit > 0 ),
    credit_id BIGINT references credit(id)
);